### ISSUE TITLE
Is this an infinite loop?

### ISSUE THREAD

**Issue by endgame** [jonathanknowles/total-monoidal-maps#108]
https://github.com/jonathanknowles/total-monoidal-maps/blob/00233e67e7afb0506c58638d2db2451f1fce7a45/src/internal/Data/Total/MonoidMap/Internal.hs#L483

**Comment by jonathanknowles** [comment]
It's surprisingly not an infinite loop!

The import pattern that I'm using here is:
```hs
import Data.Group (Group)
import Data.Group qualified as C
```
This import style doesn't import the `Group` `invert` method into the module namespace, but **_does_** make it possible to define a `Group` instance. In other words, the `invert` function defined below does not mask the `invert` method of `Group`:

https://github.com/jonathanknowles/total-monoidal-maps/blob/00233e67e7afb0506c58638d2db2451f1fce7a45/src/internal/Data/Total/MonoidMap/Internal.hs#L2691-L2694

The `Data.Map.Internal` module uses a similar technique:
https://hackage.haskell.org/package/containers-0.6.7/docs/src/Data.Map.Internal.html#local-6989586621679197169

**Comment by endgame** [comment]
Oh yeah, I get it. Cool.
